// ==============================================================================
// 경상남도교육청 학생정신건강 전담센터 - 데모용 시연 데이터 (Mock Data)
// ==============================================================================

window.INITIAL_MOCK_DATA = {
  students: [
    {
      id: "stu-001",
      client_code: "STU-2026-001",
      center_id: "jinju",
      region_id: "jinju",
      name: "김민준",
      gender: "남",
      birth_date: "2010-04-15",
      school_level: "중학교",
      school_name: "진주중학교",
      grade: 3,
      class_room: "2반",
      parent_relation: "모",
      parent_contact: "010-3412-8821",
      referral_source: "Wee클래스(학교)",
      main_concern: "자해/자살위기",
      risk_level: "SEVERE",
      assigned_worker: "이민호 사회복지사",
      assigned_psych: "박서연 임상심리사",
      notes: "팔목 부위 반복적 비자살성 자해 흔적 발견되어 Wee클래스 전문상담교사가 전담센터로 긴급 연계. 학업 스트레스 및 부모 갈등 심각.",
      created_at: "2026-08-01T09:30:00Z"
    },
    {
      id: "stu-002",
      client_code: "STU-2026-002",
      center_id: "jinju",
      region_id: "jinju",
      name: "이지은",
      gender: "여",
      birth_date: "2009-11-20",
      school_level: "고등학교",
      school_name: "진주여자고등학교",
      grade: 2,
      class_room: "5반",
      parent_relation: "부",
      parent_contact: "010-7711-2940",
      referral_source: "담임교사",
      main_concern: "우울/무기력",
      risk_level: "SEVERE",
      assigned_worker: "이민호 사회복지사",
      assigned_psych: "박서연 임상심리사",
      notes: "무기력감으로 인한 잦은 지각 및 결석. 우울감 호소하며 대인관계 단절 양상.",
      created_at: "2026-08-05T11:00:00Z"
    },
    {
      id: "stu-003",
      client_code: "STU-2026-003",
      center_id: "changwon",
      region_id: "changwon",
      name: "박준영",
      gender: "남",
      birth_date: "2011-02-14",
      school_level: "중학교",
      school_name: "창원용호중학교",
      grade: 2,
      class_room: "3반",
      parent_relation: "모",
      parent_contact: "010-9982-1234",
      referral_source: "Wee센터(교육지원청)",
      main_concern: "학교폭력/대인관계 갈등",
      risk_level: "MODERATE",
      assigned_worker: "최영희 사회복지사",
      assigned_psych: "강동원 임상심리사",
      notes: "사이버 불링 피해 이후 등교 거부감 및 불안 호소. 교우관계 회복 프로그램 지원 필요.",
      created_at: "2026-08-10T14:20:00Z"
    },
    {
      id: "stu-004",
      client_code: "STU-2026-004",
      center_id: "changwon",
      region_id: "gimhae",
      name: "최서윤",
      gender: "여",
      birth_date: "2014-07-08",
      school_level: "초등학교",
      school_name: "김해율하초등학교",
      grade: 6,
      class_room: "1반",
      parent_relation: "모",
      parent_contact: "010-4412-5501",
      referral_source: "학부모 직접의뢰",
      main_concern: "주의집중(ADHD)/충동성",
      risk_level: "MODERATE",
      assigned_worker: "최영희 사회복지사",
      assigned_psych: "강동원 임상심리사",
      notes: "수업 중 산만함과 감정 조절 어려움으로 교우들과 마찰 빈번. K-CBCL 평가 의뢰.",
      created_at: "2026-08-12T10:00:00Z"
    },
    {
      id: "stu-005",
      client_code: "STU-2026-005",
      center_id: "jinju",
      region_id: "sacheon",
      name: "정우진",
      gender: "남",
      birth_date: "2008-09-03",
      school_level: "고등학교",
      school_name: "사천삼천포고등학교",
      grade: 3,
      class_room: "4반",
      parent_relation: "조모",
      parent_contact: "010-5591-3829",
      referral_source: "담임교사",
      main_concern: "학업 및 진로 스트레스",
      risk_level: "MILD",
      assigned_worker: "이민호 사회복지사",
      assigned_psych: "박서연 임상심리사",
      notes: "수능 앞두고 신체화 증상(복통, 두통) 호소. 조손가정으로 정서적 지지 기반 취약.",
      created_at: "2026-08-15T15:30:00Z"
    },
    {
      id: "stu-006",
      client_code: "STU-2026-006",
      center_id: "jinju",
      region_id: "tongyeong",
      name: "윤아린",
      gender: "여",
      birth_date: "2010-12-01",
      school_level: "중학교",
      school_name: "통영충렬여자중학교",
      grade: 3,
      class_room: "1반",
      parent_relation: "모",
      parent_contact: "010-6623-9912",
      referral_source: "Wee클래스(학교)",
      main_concern: "불안/공황/사회불안",
      risk_level: "MODERATE",
      assigned_worker: "이민호 사회복지사",
      assigned_psych: "박서연 임상심리사",
      notes: "발표 상황에서 극심한 호흡곤란 및 발작 증상 경험. 공황 척도 및 불안 검사 시행.",
      created_at: "2026-08-18T13:40:00Z"
    },
    {
      id: "stu-007",
      client_code: "STU-2026-007",
      center_id: "changwon",
      region_id: "yangsan",
      name: "강도현",
      gender: "남",
      birth_date: "2009-03-25",
      school_level: "고등학교",
      school_name: "양산남부고등학교",
      grade: 2,
      class_room: "6반",
      parent_relation: "부",
      parent_contact: "010-8812-4433",
      referral_source: "병원 소아청소년과 연계",
      main_concern: "자해/자살위기",
      risk_level: "SEVERE",
      assigned_worker: "최영희 사회복지사",
      assigned_psych: "강동원 임상심리사",
      notes: "양산부산대병원 응급실 방문 이력 있음. 약물 과다 복용 시도 후 전담센터 외래 집중 모니터링 연계.",
      created_at: "2026-08-20T16:00:00Z"
    },
    {
      id: "stu-008",
      client_code: "STU-2026-008",
      center_id: "jinju",
      region_id: "geoje",
      name: "조은채",
      gender: "여",
      birth_date: "2011-06-19",
      school_level: "중학교",
      school_name: "거제옥포중학교",
      grade: 2,
      class_room: "4반",
      parent_relation: "모",
      parent_contact: "010-3321-7788",
      referral_source: "Wee클래스(학교)",
      main_concern: "우울/무기력",
      risk_level: "MODERATE",
      assigned_worker: "이민호 사회복지사",
      assigned_psych: "박서연 임상심리사",
      notes: "가족 내 갈등으로 인한 정서적 위축 및 식이 거부 증상.",
      created_at: "2026-08-22T10:15:00Z"
    },
    {
      id: "stu-009",
      client_code: "STU-2026-009",
      center_id: "jinju",
      region_id: "geochang",
      name: "임시우",
      gender: "남",
      birth_date: "2013-08-11",
      school_level: "초등학교",
      school_name: "거창초등학교",
      grade: 5,
      class_room: "2반",
      parent_relation: "부",
      parent_contact: "010-2234-9988",
      referral_source: "담임교사",
      main_concern: "품행문제/등교거부",
      risk_level: "MILD",
      assigned_worker: "이민호 사회복지사",
      assigned_psych: "박서연 임상심리사",
      notes: "등교 시간에 심한 떼쓰기와 분리불안 양상. 부모 양육 코칭 병행 필요.",
      created_at: "2026-08-25T11:20:00Z"
    },
    {
      id: "stu-010",
      client_code: "STU-2026-010",
      center_id: "changwon",
      region_id: "miryang",
      name: "송하늘",
      gender: "여",
      birth_date: "2008-01-30",
      school_level: "고등학교",
      school_name: "밀양여자고등학교",
      grade: 3,
      class_room: "1반",
      parent_relation: "모",
      parent_contact: "010-7765-1122",
      referral_source: "Wee클래스(학교)",
      main_concern: "우울/무기력",
      risk_level: "NORMAL",
      assigned_worker: "최영희 사회복지사",
      assigned_psych: "강동원 임상심리사",
      notes: "초기 우울 호소 있었으나 센터 5회기 모니터링 후 정서 안정화되어 종결 평가 단계.",
      created_at: "2026-08-02T14:00:00Z"
    }
  ],

  // 심리검사 결과 데이터
  tests: [
    {
      id: "t-001",
      client_id: "stu-001",
      client_code: "STU-2026-001",
      client_name: "김민준",
      test_type: "AMPQ_II",
      test_date: "2026-08-03",
      examiner: "박서연 임상심리사",
      total_score: 38,
      t_score: 74.5,
      percentile: 98.2,
      verdict: "HIGH_RISK",
      subscale_scores: {
        depression: 12,
        anxiety: 10,
        conduct: 9,
        deliberation: 7
      },
      file_name: "2026_08_진주중_김민준_정서행동특성검사.xlsx",
      summary_opinion: "자살/자해 생각 영역(7점)이 절단점(4점)을 크게 상회하는 위기군. 비자살성 자해를 통한 정서 조절 시도 관찰됨. 즉각적인 전문의 자문 및 병원 진료 연계 권고."
    },
    {
      id: "t-002",
      client_id: "stu-001",
      client_code: "STU-2026-001",
      client_name: "김민준",
      test_type: "C_SSRS",
      test_date: "2026-08-04",
      examiner: "박서연 임상심리사",
      total_score: 4,
      t_score: null,
      percentile: null,
      verdict: "HIGH_RISK",
      subscale_scores: { severity_level: 4, intent: 1 },
      file_name: null,
      summary_opinion: "C-SSRS 4단계(자살 의도가 동반된 능동적 자살 사고). 안전계획서 수립 및 보호자 24시간 밀착 보호 조치 요망."
    },
    {
      id: "t-003",
      client_id: "stu-002",
      client_code: "STU-2026-002",
      client_name: "이지은",
      test_type: "K_BDI_II",
      test_date: "2026-08-06",
      examiner: "박서연 임상심리사",
      total_score: 34,
      t_score: 72.0,
      percentile: 96.5,
      verdict: "HIGH_RISK",
      subscale_scores: { cognitive: 18, somatic: 16 },
      file_name: "20260806_진주여고_이지은_BDI_결과지.pdf",
      summary_opinion: "중증의 우울 상태. 지속적인 무기력, 수면 장애, 미래에 대한 절망감 보고. 인지치료적 접근 및 약물치료 의뢰 필요."
    },
    {
      id: "t-004",
      client_id: "stu-003",
      client_code: "STU-2026-003",
      client_name: "박준영",
      test_type: "RCMAS",
      test_date: "2026-08-11",
      examiner: "강동원 임상심리사",
      total_score: 16,
      t_score: 64.0,
      percentile: 88.0,
      verdict: "ATTENTION",
      subscale_scores: { worry: 8, physiological: 5, social: 3 },
      file_name: null,
      summary_opinion: "또래 관계 스트레스로 인한 과민성 불안 및 신체적 각성 반응 상승. 학교 적응 및 이완 훈련 중심의 단기 상담 권고."
    },
    {
      id: "t-005",
      client_id: "stu-004",
      client_code: "STU-2026-004",
      client_name: "최서윤",
      test_type: "K_CBCL",
      test_date: "2026-08-14",
      examiner: "강동원 임상심리사",
      total_score: 68,
      t_score: 68.0,
      percentile: 95.0,
      verdict: "ATTENTION",
      subscale_scores: { attention_problems: 72, rule_breaking: 62, aggressive: 65 },
      file_name: "율하초_최서윤_KCBCL_검사지.xlsx",
      summary_opinion: "주의집중 문제 척도 T점수 72점으로 임상 범위. 충동성 조절 훈련과 부모-자녀 상호작용 개선 지도 권고."
    },
    {
      id: "t-006",
      client_id: "stu-007",
      client_code: "STU-2026-007",
      client_name: "강도현",
      test_type: "C_SSRS",
      test_date: "2026-08-21",
      examiner: "강동원 임상심리사",
      total_score: 5,
      t_score: null,
      percentile: null,
      verdict: "HIGH_RISK",
      subscale_scores: { severity_level: 5, attempt: 1 },
      file_name: null,
      summary_opinion: "C-SSRS 5단계(실제 자살 시도력 있음). 병원 정신건강의학과 외래 치료 지속 및 전담센터 주 2회 집중 모니터링 체계 가동."
    },
    {
      id: "t-007",
      client_id: "stu-010",
      client_code: "STU-2026-010",
      client_name: "송하늘",
      test_type: "K_BDI_II",
      test_date: "2026-08-03",
      examiner: "강동원 임상심리사",
      total_score: 22,
      t_score: 61.0,
      percentile: 79.0,
      verdict: "ATTENTION",
      subscale_scores: { cognitive: 12, somatic: 10 },
      file_name: null,
      summary_opinion: "사전 검사: 중등도 우울 증상 호소."
    },
    {
      id: "t-008",
      client_id: "stu-010",
      client_code: "STU-2026-010",
      client_name: "송하늘",
      test_type: "K_BDI_II",
      test_date: "2026-08-28",
      examiner: "강동원 임상심리사",
      total_score: 8,
      t_score: 44.0,
      percentile: 35.0,
      verdict: "NORMAL",
      subscale_scores: { cognitive: 4, somatic: 4 },
      file_name: null,
      summary_opinion: "사후 검사: 5회기 모니터링 후 총점 22점 -> 8점으로 현저한 감소(정상 범위 도달). 치료 개입 효과 긍정적."
    }
  ],

  // 모니터링 및 상담 일지
  monitoringLogs: [
    {
      id: "log-001",
      client_id: "stu-001",
      client_name: "김민준",
      worker: "이민호 사회복지사",
      session_no: 1,
      session_date: "2026-08-04",
      contact_type: "FACE_TO_FACE",
      current_risk: "SEVERE",
      session_summary: "진주센터 내방 초기 접수면담 및 라포 형성.",
      student_status: "표정이 어둡고 대화를 피하려 함. 최근 2주간 수면장애 및 자해 충동 매일 느낌.",
      intervention_details: "자해 안전서약서 작성, 스트레스 일기장 제공, 보호자(어머니) 대상 비난 자제 및 경청 훈육 코칭 진행.",
      doctor_opinion: "[김진우 센터장 소견] 고위험 청소년으로 판단됨. 충동성 완화를 위한 약물치료 병행 필요하므로 병원 외래 진료 우선 권유할 것.",
      next_schedule: "2026-08-11"
    },
    {
      id: "log-002",
      client_id: "stu-001",
      client_name: "김민준",
      worker: "이민호 사회복지사",
      session_no: 2,
      session_date: "2026-08-11",
      contact_type: "VISIT_SCHOOL",
      current_risk: "MODERATE",
      session_summary: "진주중학교 방문하여 Wee클래스 전문상담교사와 다학제 회의 및 학생 상담.",
      student_status: "자해 충동이 1회 있었으나 안전 서약 떠올리며 얼음 쥐기로 대체했다고 진술함.",
      intervention_details: "담임교사 면담을 통해 학급 내 과도한 발표 지양 요청, Wee클래스 주 1회 상담 연계 강화.",
      doctor_opinion: "[김진우 센터장 소견] 대체 행동 전략 효과 확인됨. 우울 증상 모니터링 지속 요망.",
      next_schedule: "2026-08-18"
    },
    {
      id: "log-003",
      client_id: "stu-002",
      client_name: "이지은",
      worker: "이민호 사회복지사",
      session_no: 1,
      session_date: "2026-08-07",
      contact_type: "PHONE",
      current_risk: "SEVERE",
      session_summary: "학생 및 부모 1차 전화 모니터링.",
      student_status: "하루 대부분을 침대에서 보내며 식욕 부진 호소.",
      intervention_details: "작은 일상 루틴(햇빛 쬐기, 15분 산책) 설정, 진주 경상국립대병원 소아청소년정신과 외래 접수 지원 안내.",
      doctor_opinion: "[김진우 센터장 소견] 8월 13일 병원 외래 초진 예정. 진료 후 소견서 공유하여 상담 계획 재수립 예정.",
      next_schedule: "2026-08-14"
    },
    {
      id: "log-004",
      client_id: "stu-007",
      client_name: "강도현",
      worker: "최영희 사회복지사",
      session_no: 1,
      session_date: "2026-08-22",
      contact_type: "FACE_TO_FACE",
      current_risk: "SEVERE",
      session_summary: "창원센터 긴급 위기개입 대면 면담 진행.",
      student_status: "퇴원 직후 상태로 감정적 취약성 높음.",
      intervention_details: "위기 핫라인(1393, 센터 긴급 직통전화) 숙지, 부모와 함께 가정 내 위험 물품 격리 조치 확인.",
      doctor_opinion: "[창원센터장 소견] 초고위험군. 주 2회 전화 체크 및 주 1회 대면 상담 필수 유지.",
      next_schedule: "2026-08-26"
    }
  ]
};
